version: '3.0'
services:
  redis:
    image: redis:7.2.0-alpine
    container_name: redis
    hostname: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 10

  spring:
    container_name: spring
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      redis:
        condition: service_healthy
  react:
    container_name: react
    expose:
      - 3000

  nginx:
    container_name: nginx
    image: mclub4/eum-nginx:1.0
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - "redis"
      - "spring"
      - "react"