version: '3'
services:
  redis:
    image: redis:7.2.0-alpine
    container_name: redis
    hostname: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 10

  spring:
    container_name: spring
    restart: always
    image: gcpkmu/eum-spring
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      redis:
        condition: service_healthy

  react:
    container_name: react
    image: gcpkmu/eum-react
    expose:
      - 3000

  nginx:
    container_name: nginx
    image: gcpkmu/eum-nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - "redis"
      - "spring"
      - "react"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  cerbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
