version: '3'
services:
  redis:
    image: redis:7.2.0-alpine
    container_name: redis
    hostname: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 10

  spring:
    container_name: spring
    restart: always
    image: gcpkmu/eum-spring:test
    env_file:
      - business/src/.env
    ports:
      - 8080:8080
    depends_on:
      redis:
        condition: service_healthy
