package com.example.eumserver.domain.team.announcement.domain;

/**
 * 모집 공고의 직종 분류를 모아둔 Enum Class 입니다.
 * {@link AnnouncementOccupationClassification}
 */
public enum OccupationClassifications {
    DESIGN_UI_UX,
    DESIGN_ILLUSTRATION_CHARACTER,
    DESIGN_MOVIE_MOTION_GRAPHIC,
    DESIGN_PRODUCT_PACKAGE,
    DESIGN_PASSION,
    DESIGN_CRAFTS,
    DESIGN_GRAPHIC,

    DEVELOPMENT_FRONTEND,
    DEVELOPMENT_BACKEND,
    DEVELOPMENT_AI,
    DEVELOPMENT_DEVOPS,
    DEVELOPMENT_SECURITY,
    DEVELOPMENT_GAME,
    DEVELOPMENT_EMBEDDED,
    DEVELOPMENT_DBA,

    PLAN,

    MEDIA_EDITING_MOVIE,
    MEDIA_FILMING_MOVIE,
    MEDIA_PD,
    MEDIA_PHOTOGRAPHER,
    MEDIA_SOUND_ENGINEER,

    MARKETING_MANAGEMENT,
    MARKETING_PROMOTION,
    MARKETING_CONSULTING,

    TRANSLATION_ENGLISH,
    TRANSLATION_JAPANESE,
    TRANSLATION_CHINESE,
    TRANSLATION_SPANISH,
    TRANSLATION_ALABIC,
    TRANSLATION_HINDI,
    TRANSLATION_FRANCH,
    TRANSLATION_ETC,

    ETC
}
